[package]
name = "tgnews"
version = "0.2.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]

whatlang = "0.7.2"
select = "0.4.3"
futures = "0.3.1"
tendril = "0.4.1"
chrono = "0.4.9"
redis = "0.13.0"